class Fraction:
    def __init__(self,numerator,denominator,mark):
        self.Numerator = numerator
        self.Denominator = denominator
        self.Mark = mark
        pass
    def F_Sum(self,num1,den1,num2,den2):
        ...
    def F_Sub(self,num1,den1,num2,den2):
        ...
    def F_Multi(self,num1,den1,num2,den2):
        ...
    def F_div(self,num1,den1,num2,den2):
        ...
    def check_define(self,num,den):
        ...
    def check_reverse_define(self,num,den):
        ...
    def convert_to_decimal_num(self,num,den):
        ...
    def comparison(self,num,den):
        ...
    