class Date:
    def __init__(self,year,month,day):
        self.Year = year
        self.Month = month
        self.Day = day
        pass
    def Persian_to_Julian(self,year,month,day):
        ...
    def Julian_to_Persian(self,year,month,day):
        ...
    def Persian_to_Islamic(self,year,month,day):
        ...
    def Islamic_to_Persian(self,year,month,day):
        ...
    def Julian_to_Islamic(self,year,month,day):
        ...
    def Islamic_to_Julian(self,year,month,day):
        ...
    def difference_between_two_dates_y(self,year1,month1,day1,year2,month2,day2):
        ...
    def difference_between_two_dates_m(self,year1,month1,day1,year2,month2,day2):
        ...
    def difference_between_two_dates_d(self,year1,month1,day1,year2,month2,day2):
        ...    
    def days_since_the_beginning_oflastyear(self,year,month,day):
        ...
    def months_since_the_beginning_oflastyear(self,year,month,day):
        ...
    def days_left_until_the_end_of_the_year(self,year,month,day):
        ...
    def months_left_until_the_end_of_the_year(self,year,month,day):
        ...